directories:
  output: dist-electron
  buildResources: build
appId: com.bellaart.erp
productName: Sistema Bella Art in madeira
copyright: Bella Art in Madeira
files:
  - filter:
      - electron/**/*
      - frontend/**/*
      - app/**/*
      - data/.gitkeep
extraResources:
  - from: python-dist/
    to: python-dist/
    filter:
      - '**/*'
  - from: data/
    to: data/
    filter:
      - bellart.ini
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: frontend/static/logo.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Sistema Bella Art in madeira
  installerIcon: frontend/static/logo.ico
  uninstallerIcon: frontend/static/logo.ico
  installerHeaderIcon: frontend/static/logo.ico
  deleteAppDataOnUninstall: false
electronVersion: 33.4.11
